### ISSUE TITLE
Rankup not updating

### ISSUE THREAD

**Issue by PrisonHeist** [messageofdeath/PaidRanks#2]
Hi, I've configured my ladder for A-Z, when I rank up it shows me getting the correct rank and /pex user <name> also confirms this, however in game i continue to show as [A] unless I do a /pex reload

Any ideas why this doesn't update? also in the new version of PaidRanks you can't make it broadcast rankups?

**Comment by messageofdeath** [comment]
This issue has been resolved with the release of v3.4
