### ISSUE TITLE
Do not have permission to buy rank

### ISSUE THREAD

**Issue by Dragonfire967** [messageofdeath/PaidRanks#4]
Hey, I am setting up a server running bukkit 1.11.2, with the latest version of PaidRanks (v3.7) and PermissionsEx(v1.23.4). I am also using MyCommand(v5.3.4) to create aliases for PaidRank commands (to make them shorter and easier to type out)

All information pertaining to the below can be found in attached files:

I un-opped myself, set my server group to the lowest rank on the rank ladder and typed /rankup, then confirmed said rank with /rankup yes (both commands are in MyCommand, as alias commands of the /ru command in PaidRanks). I proceed to get the following error:

`[Error] You do not have permission to buy this rank!`

I double checked my permissions.yml file. I have all the needed perms, I have no clue what is causing the issue. It worked fine earlier, and no drastic changes have been made since it last worked.

In information on what is going on, and how to fix it, would be greatly appreciated.

Attachment: [error.zip](https://github.com/messageofdeath/PaidRanks/files/1072791/error.zip)

**Comment by messageofdeath** [comment]
The issue you are currently having, is that within the "ranks.yml" you are setting the 'Perm' to something that they do not have. You're using 'Perm' as a description, where as it's used as a custom permission, if you wanted to have one.

Can be fixed one of two ways.
1) Change them to permission nodes and add them to your "permissions.yml"
2) Remove the 'Perm' node from the "ranks.yml" from every single rank.
